version: 0.2

phases:
  runtime-versions:
    nodejs: 16
  # install:
  #   runtime-versions:
  #     nodejs: 16
  #   # commands:
  #   #   - npm i npm@latest -g
  #   #   - pip install --upgrade pip
  #   #   - pip install --upgrade awscli
  #   #   - echo Ready
  pre_build:
    commands:
      - printenv
      - echo `date +%s` > timestamp
      - echo Build started on `date`
      - npm cache verify
      - npm install
  build:
    commands:
      - npm run generate
  post_build:
    commands:
      - aws s3 sync --cache-control max-age=604800,public --delete ./dist $S3_BUCKET
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
