export const abi = [
  {
    inputs: [
      { internalType: 'address', name: '_token', type: 'address' },
      { internalType: 'address', name: '_signer', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'wallet', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
      { indexed: true, internalType: 'bytes32', name: 'dataHash', type: 'bytes32' },
    ],
    name: 'Claim',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'bytes32', name: 'dataHash', type: 'bytes32' }],
    name: 'DataHashInvalidated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'signer', type: 'address' }],
    name: 'SetSigner',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'wallet', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'WithdrawToken',
    type: 'event',
  },
  {
    inputs: [],
    name: 'TOKEN',
    outputs: [{ internalType: 'contract IERC20', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
      { internalType: 'uint256', name: 'timestamp', type: 'uint256' },
      { internalType: 'bytes', name: 'signature', type: 'bytes' },
    ],
    name: 'claim',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'dataHashInvalidated',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'dataHash', type: 'bytes32' }],
    name: 'invalidateDataHash',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_signer', type: 'address' }],
    name: 'setSigner',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'signer',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'sender', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
      { internalType: 'uint256', name: 'timestamp', type: 'uint256' },
      { internalType: 'bytes', name: 'signature', type: 'bytes' },
    ],
    name: 'validateSignature',
    outputs: [
      { internalType: 'bytes32', name: '', type: 'bytes32' },
      { internalType: 'bool', name: '', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'walletClaimed',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'wallet', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'withdrawToken',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];
export const nftAbiNestable = [
  {
    type: 'constructor',
    inputs: [
      { name: '_name', type: 'string', internalType: 'string' },
      { name: '_symbol', type: 'string', internalType: 'string' },
      { name: '_initBaseURI', type: 'string', internalType: 'string' },
      { name: '_baseExtension', type: 'string', internalType: 'string' },
      { name: '_settings', type: 'bool[]', internalType: 'bool[]' },
      { name: '_dropStart', type: 'uint256', internalType: 'uint256' },
      { name: '_reserve', type: 'uint256', internalType: 'uint256' },
      {
        name: '_data',
        type: 'tuple',
        components: [
          { name: 'royaltyRecipient', type: 'address', internalType: 'address' },
          { name: 'royaltyPercentageBps', type: 'uint16', internalType: 'uint16' },
          { name: 'maxSupply', type: 'uint256', internalType: 'uint256' },
          { name: 'pricePerMint', type: 'uint256', internalType: 'uint256' },
        ],
        internalType: 'struct InitDataNativePay.InitData',
      },
    ],
    stateMutability: 'nonpayable',
  },
  { name: 'ERC721AddressZeroIsNotaValidOwner', type: 'error', inputs: [] },
  { name: 'ERC721ApprovalToCurrentOwner', type: 'error', inputs: [] },
  { name: 'ERC721ApproveCallerIsNotOwnerNorApprovedForAll', type: 'error', inputs: [] },
  { name: 'ERC721ApproveToCaller', type: 'error', inputs: [] },
  { name: 'ERC721InvalidTokenId', type: 'error', inputs: [] },
  { name: 'ERC721MintToTheZeroAddress', type: 'error', inputs: [] },
  { name: 'ERC721NotApprovedOrOwner', type: 'error', inputs: [] },
  { name: 'ERC721TokenAlreadyMinted', type: 'error', inputs: [] },
  { name: 'ERC721TransferFromIncorrectOwner', type: 'error', inputs: [] },
  { name: 'ERC721TransferToNonReceiverImplementer', type: 'error', inputs: [] },
  { name: 'ERC721TransferToTheZeroAddress', type: 'error', inputs: [] },
  { name: 'RMRKChildAlreadyExists', type: 'error', inputs: [] },
  { name: 'RMRKChildIndexOutOfRange', type: 'error', inputs: [] },
  { name: 'RMRKIdZeroForbidden', type: 'error', inputs: [] },
  { name: 'RMRKIsNotContract', type: 'error', inputs: [] },
  { name: 'RMRKMaxPendingChildrenReached', type: 'error', inputs: [] },
  {
    name: 'RMRKMaxRecursiveBurnsReached',
    type: 'error',
    inputs: [
      { name: 'childContract', type: 'address', internalType: 'address' },
      { name: 'childId', type: 'uint256', internalType: 'uint256' },
    ],
  },
  { name: 'RMRKMintOverMax', type: 'error', inputs: [] },
  { name: 'RMRKMintToNonRMRKNestableImplementer', type: 'error', inputs: [] },
  { name: 'RMRKMintZero', type: 'error', inputs: [] },
  { name: 'RMRKNestableTooDeep', type: 'error', inputs: [] },
  { name: 'RMRKNestableTransferToDescendant', type: 'error', inputs: [] },
  { name: 'RMRKNestableTransferToNonRMRKNestableImplementer', type: 'error', inputs: [] },
  { name: 'RMRKNestableTransferToSelf', type: 'error', inputs: [] },
  { name: 'RMRKNewContributorIsZeroAddress', type: 'error', inputs: [] },
  { name: 'RMRKNewOwnerIsZeroAddress', type: 'error', inputs: [] },
  { name: 'RMRKNotApprovedOrDirectOwner', type: 'error', inputs: [] },
  { name: 'RMRKNotOwner', type: 'error', inputs: [] },
  { name: 'RMRKPendingChildIndexOutOfRange', type: 'error', inputs: [] },
  { name: 'RMRKRoyaltiesTooHigh', type: 'error', inputs: [] },
  { name: 'RMRKUnexpectedChildId', type: 'error', inputs: [] },
  { name: 'RMRKUnexpectedNumberOfChildren', type: 'error', inputs: [] },
  { name: 'RMRKWrongValueSent', type: 'error', inputs: [] },
  {
    name: 'AllChildrenRejected',
    type: 'event',
    inputs: [{ name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' }],
    anonymous: false,
  },
  {
    name: 'Approval',
    type: 'event',
    inputs: [
      { name: 'owner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'approved', type: 'address', indexed: true, internalType: 'address' },
      { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    name: 'ApprovalForAll',
    type: 'event',
    inputs: [
      { name: 'owner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'operator', type: 'address', indexed: true, internalType: 'address' },
      { name: 'approved', type: 'bool', indexed: false, internalType: 'bool' },
    ],
    anonymous: false,
  },
  {
    name: 'ChildAccepted',
    type: 'event',
    inputs: [
      { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'childIndex', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'childAddress', type: 'address', indexed: true, internalType: 'address' },
      { name: 'childId', type: 'uint256', indexed: true, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    name: 'ChildProposed',
    type: 'event',
    inputs: [
      { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'childIndex', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'childAddress', type: 'address', indexed: true, internalType: 'address' },
      { name: 'childId', type: 'uint256', indexed: true, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    name: 'ChildTransferred',
    type: 'event',
    inputs: [
      { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'childIndex', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'childAddress', type: 'address', indexed: true, internalType: 'address' },
      { name: 'childId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'fromPending', type: 'bool', indexed: false, internalType: 'bool' },
      { name: 'toZero', type: 'bool', indexed: false, internalType: 'bool' },
    ],
    anonymous: false,
  },
  {
    name: 'ContributorUpdate',
    type: 'event',
    inputs: [
      { name: 'contributor', type: 'address', indexed: true, internalType: 'address' },
      { name: 'isContributor', type: 'bool', indexed: false, internalType: 'bool' },
    ],
    anonymous: false,
  },
  {
    name: 'NestTransfer',
    type: 'event',
    inputs: [
      { name: 'from', type: 'address', indexed: true, internalType: 'address' },
      { name: 'to', type: 'address', indexed: true, internalType: 'address' },
      { name: 'fromTokenId', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'toTokenId', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    name: 'OwnershipTransferred',
    type: 'event',
    inputs: [
      { name: 'previousOwner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'newOwner', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    name: 'Transfer',
    type: 'event',
    inputs: [
      { name: 'from', type: 'address', indexed: true, internalType: 'address' },
      { name: 'to', type: 'address', indexed: true, internalType: 'address' },
      { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    name: 'RMRK_INTERFACE',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'bytes4', internalType: 'bytes4' }],
    stateMutability: 'view',
  },
  {
    name: 'VERSION',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    name: 'acceptChild',
    type: 'function',
    inputs: [
      { name: 'parentId', type: 'uint256', internalType: 'uint256' },
      { name: 'childIndex', type: 'uint256', internalType: 'uint256' },
      { name: 'childAddress', type: 'address', internalType: 'address' },
      { name: 'childId', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'addChild',
    type: 'function',
    inputs: [
      { name: 'parentId', type: 'uint256', internalType: 'uint256' },
      { name: 'childId', type: 'uint256', internalType: 'uint256' },
      { name: 'data', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'allTokens',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256[]', internalType: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    name: 'approve',
    type: 'function',
    inputs: [
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'balanceOf',
    type: 'function',
    inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'baseExtension',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    name: 'burn',
    type: 'function',
    inputs: [{ name: 'tokenId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'burn',
    type: 'function',
    inputs: [
      { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
      { name: 'maxChildrenBurns', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    name: 'childOf',
    type: 'function',
    inputs: [
      { name: 'parentId', type: 'uint256', internalType: 'uint256' },
      { name: 'index', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
          { name: 'contractAddress', type: 'address', internalType: 'address' },
        ],
        internalType: 'struct IERC6059.Child',
      },
    ],
    stateMutability: 'view',
  },
  {
    name: 'childrenOf',
    type: 'function',
    inputs: [{ name: 'parentId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple[]',
        components: [
          { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
          { name: 'contractAddress', type: 'address', internalType: 'address' },
        ],
        internalType: 'struct IERC6059.Child[]',
      },
    ],
    stateMutability: 'view',
  },
  {
    name: 'collectionMetadata',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    name: 'directOwnerOf',
    type: 'function',
    inputs: [{ name: 'tokenId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'bool', internalType: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    name: 'dropStart',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'getApproved',
    type: 'function',
    inputs: [{ name: 'tokenId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    name: 'getRoyaltyPercentage',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'getRoyaltyRecipient',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    name: 'isApprovedForAll',
    type: 'function',
    inputs: [
      { name: 'owner', type: 'address', internalType: 'address' },
      { name: 'operator', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    name: 'isContributor',
    type: 'function',
    inputs: [{ name: 'contributor', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    name: 'isDrop',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    name: 'isRevokable',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    name: 'isSoulbound',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    name: 'manageContributor',
    type: 'function',
    inputs: [
      { name: 'contributor', type: 'address', internalType: 'address' },
      { name: 'grantRole', type: 'bool', internalType: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'maxSupply',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'mint',
    type: 'function',
    inputs: [
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'numToMint', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    name: 'name',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    name: 'nestMint',
    type: 'function',
    inputs: [
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'numToMint', type: 'uint256', internalType: 'uint256' },
      { name: 'destinationId', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    name: 'nestTransferFrom',
    type: 'function',
    inputs: [
      { name: 'from', type: 'address', internalType: 'address' },
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
      { name: 'destinationId', type: 'uint256', internalType: 'uint256' },
      { name: 'data', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'owner',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    name: 'ownerMint',
    type: 'function',
    inputs: [
      { name: '_receiver', type: 'address', internalType: 'address' },
      { name: '_numToMint', type: 'uint16', internalType: 'uint16' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'ownerNestMint',
    type: 'function',
    inputs: [
      { name: '_receiver', type: 'address', internalType: 'address' },
      { name: '_numToMint', type: 'uint16', internalType: 'uint16' },
      { name: 'destinationId', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'ownerOf',
    type: 'function',
    inputs: [{ name: 'tokenId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    name: 'pendingChildOf',
    type: 'function',
    inputs: [
      { name: 'parentId', type: 'uint256', internalType: 'uint256' },
      { name: 'index', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
          { name: 'contractAddress', type: 'address', internalType: 'address' },
        ],
        internalType: 'struct IERC6059.Child',
      },
    ],
    stateMutability: 'view',
  },
  {
    name: 'pendingChildrenOf',
    type: 'function',
    inputs: [{ name: 'parentId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple[]',
        components: [
          { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
          { name: 'contractAddress', type: 'address', internalType: 'address' },
        ],
        internalType: 'struct IERC6059.Child[]',
      },
    ],
    stateMutability: 'view',
  },
  {
    name: 'pricePerMint',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'rejectAllChildren',
    type: 'function',
    inputs: [
      { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
      { name: 'maxRejections', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  { name: 'renounceOwnership', type: 'function', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  {
    name: 'reserve',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'royaltyInfo',
    type: 'function',
    inputs: [
      { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
      { name: 'salePrice', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [
      { name: 'receiver', type: 'address', internalType: 'address' },
      { name: 'royaltyAmount', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    name: 'safeTransferFrom',
    type: 'function',
    inputs: [
      { name: 'from', type: 'address', internalType: 'address' },
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'safeTransferFrom',
    type: 'function',
    inputs: [
      { name: 'from', type: 'address', internalType: 'address' },
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
      { name: 'data', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'setApprovalForAll',
    type: 'function',
    inputs: [
      { name: 'operator', type: 'address', internalType: 'address' },
      { name: 'approved', type: 'bool', internalType: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'setBaseExtension',
    type: 'function',
    inputs: [{ name: '_newBaseExtension', type: 'string', internalType: 'string' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'setBaseURI',
    type: 'function',
    inputs: [{ name: '_newBaseURI', type: 'string', internalType: 'string' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'setDropStart',
    type: 'function',
    inputs: [{ name: '_dropStart', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'supportsInterface',
    type: 'function',
    inputs: [{ name: 'interfaceId', type: 'bytes4', internalType: 'bytes4' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    name: 'symbol',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    name: 'tokenByIndex',
    type: 'function',
    inputs: [{ name: 'index', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'tokenOfOwnerByIndex',
    type: 'function',
    inputs: [
      { name: 'owner', type: 'address', internalType: 'address' },
      { name: 'index', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'tokenURI',
    type: 'function',
    inputs: [{ name: 'tokenId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    name: 'totalAssets',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'totalSupply',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'transferChild',
    type: 'function',
    inputs: [
      { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'destinationId', type: 'uint256', internalType: 'uint256' },
      { name: 'childIndex', type: 'uint256', internalType: 'uint256' },
      { name: 'childAddress', type: 'address', internalType: 'address' },
      { name: 'childId', type: 'uint256', internalType: 'uint256' },
      { name: 'isPending', type: 'bool', internalType: 'bool' },
      { name: 'data', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'transferFrom',
    type: 'function',
    inputs: [
      { name: 'from', type: 'address', internalType: 'address' },
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'transferOwnership',
    type: 'function',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'updateRoyaltyRecipient',
    type: 'function',
    inputs: [{ name: 'newRoyaltyRecipient', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'walletOfOwner',
    type: 'function',
    inputs: [{ name: '_owner', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256[]', internalType: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    name: 'withdrawRaised',
    type: 'function',
    inputs: [
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
];

export const nftAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: '_name', type: 'string', internalType: 'string' },
      { name: '_symbol', type: 'string', internalType: 'string' },
      { name: '_initBaseURI', type: 'string', internalType: 'string' },
      { name: '_baseExtension', type: 'string', internalType: 'string' },
      { name: '_settings', type: 'bool[]', internalType: 'bool[]' },
      { name: '_numbers', type: 'uint256[]', internalType: 'uint256[]' },
      { name: '_royaltiesAddress', type: 'address', internalType: 'address' },
      { name: '_admin', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    name: 'Approval',
    type: 'event',
    inputs: [
      { name: 'owner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'approved', type: 'address', indexed: true, internalType: 'address' },
      { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    name: 'ApprovalForAll',
    type: 'event',
    inputs: [
      { name: 'owner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'operator', type: 'address', indexed: true, internalType: 'address' },
      { name: 'approved', type: 'bool', indexed: false, internalType: 'bool' },
    ],
    anonymous: false,
  },
  {
    name: 'RoleAdminChanged',
    type: 'event',
    inputs: [
      { name: 'role', type: 'bytes32', indexed: true, internalType: 'bytes32' },
      { name: 'previousAdminRole', type: 'bytes32', indexed: true, internalType: 'bytes32' },
      { name: 'newAdminRole', type: 'bytes32', indexed: true, internalType: 'bytes32' },
    ],
    anonymous: false,
  },
  {
    name: 'RoleGranted',
    type: 'event',
    inputs: [
      { name: 'role', type: 'bytes32', indexed: true, internalType: 'bytes32' },
      { name: 'account', type: 'address', indexed: true, internalType: 'address' },
      { name: 'sender', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    name: 'RoleRevoked',
    type: 'event',
    inputs: [
      { name: 'role', type: 'bytes32', indexed: true, internalType: 'bytes32' },
      { name: 'account', type: 'address', indexed: true, internalType: 'address' },
      { name: 'sender', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    name: 'Transfer',
    type: 'event',
    inputs: [
      { name: 'from', type: 'address', indexed: true, internalType: 'address' },
      { name: 'to', type: 'address', indexed: true, internalType: 'address' },
      { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    name: 'CONTROLLER_ROLE',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    name: 'DEFAULT_ADMIN_ROLE',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    name: 'allTokens',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256[]', internalType: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    name: 'approve',
    type: 'function',
    inputs: [
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'balanceOf',
    type: 'function',
    inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'baseExtension',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    name: 'burn',
    type: 'function',
    inputs: [{ name: 'tokenId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'dropStart',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'getApproved',
    type: 'function',
    inputs: [{ name: 'tokenId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    name: 'getRoleAdmin',
    type: 'function',
    inputs: [{ name: 'role', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    name: 'getRoyaltyPercentage',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'getRoyaltyRecipient',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    name: 'grantRole',
    type: 'function',
    inputs: [
      { name: 'role', type: 'bytes32', internalType: 'bytes32' },
      { name: 'account', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'hasRole',
    type: 'function',
    inputs: [
      { name: 'role', type: 'bytes32', internalType: 'bytes32' },
      { name: 'account', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    name: 'isApprovedForAll',
    type: 'function',
    inputs: [
      { name: 'owner', type: 'address', internalType: 'address' },
      { name: 'operator', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    name: 'isAutoIncrement',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    name: 'isDrop',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    name: 'isRevokable',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    name: 'isSoulbound',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    name: 'maxSupply',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'mint',
    type: 'function',
    inputs: [
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'numToMint', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    name: 'mintCounter',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'mintIds',
    type: 'function',
    inputs: [
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'numToMint', type: 'uint256', internalType: 'uint256' },
      { name: 'idsToMint', type: 'uint256[]', internalType: 'uint256[]' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    name: 'name',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    name: 'ownerMint',
    type: 'function',
    inputs: [
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'numToMint', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'ownerMintIds',
    type: 'function',
    inputs: [
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'numToMint', type: 'uint256', internalType: 'uint256' },
      { name: 'idsToMint', type: 'uint256[]', internalType: 'uint256[]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'ownerMintIdsWithUri',
    type: 'function',
    inputs: [
      {
        name: 'mints',
        type: 'tuple[]',
        components: [
          { name: 'to', type: 'address', internalType: 'address' },
          { name: 'numToMint', type: 'uint256', internalType: 'uint256' },
          { name: 'idsToMint', type: 'uint256[]', internalType: 'uint256[]' },
          { name: 'URIs', type: 'string[]', internalType: 'string[]' },
        ],
        internalType: 'struct ApillonNFT.MintParameters[]',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'ownerOf',
    type: 'function',
    inputs: [{ name: 'tokenId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    name: 'pricePerMint',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'renounceRole',
    type: 'function',
    inputs: [
      { name: 'role', type: 'bytes32', internalType: 'bytes32' },
      { name: 'account', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'reserve',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'revokeRole',
    type: 'function',
    inputs: [
      { name: 'role', type: 'bytes32', internalType: 'bytes32' },
      { name: 'account', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'royaltiesAddress',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    name: 'royaltiesFees',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'royaltyInfo',
    type: 'function',
    inputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: 'value', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [
      { name: 'receiver', type: 'address', internalType: 'address' },
      { name: 'royaltyAmount', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    name: 'safeTransferFrom',
    type: 'function',
    inputs: [
      { name: 'from', type: 'address', internalType: 'address' },
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'safeTransferFrom',
    type: 'function',
    inputs: [
      { name: 'from', type: 'address', internalType: 'address' },
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
      { name: 'data', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'setApprovalForAll',
    type: 'function',
    inputs: [
      { name: 'operator', type: 'address', internalType: 'address' },
      { name: 'approved', type: 'bool', internalType: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'setBaseExtension',
    type: 'function',
    inputs: [{ name: '_newBaseExtension', type: 'string', internalType: 'string' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'setBaseURI',
    type: 'function',
    inputs: [{ name: '_newBaseURI', type: 'string', internalType: 'string' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'setDropStart',
    type: 'function',
    inputs: [{ name: '_dropStart', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'setTokenURI',
    type: 'function',
    inputs: [
      { name: '_tokenId', type: 'uint256', internalType: 'uint256' },
      { name: '_newTokenURI', type: 'string', internalType: 'string' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'supportsInterface',
    type: 'function',
    inputs: [{ name: 'interfaceId', type: 'bytes4', internalType: 'bytes4' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    name: 'symbol',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    name: 'tokenByIndex',
    type: 'function',
    inputs: [{ name: 'index', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'tokenOfOwnerByIndex',
    type: 'function',
    inputs: [
      { name: 'owner', type: 'address', internalType: 'address' },
      { name: 'index', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'tokenURI',
    type: 'function',
    inputs: [{ name: 'tokenId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    name: 'totalSupply',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'transferAdmin',
    type: 'function',
    inputs: [{ name: '_newAdmin', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'transferFrom',
    type: 'function',
    inputs: [
      { name: 'from', type: 'address', internalType: 'address' },
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'updateRoyaltyRecipient',
    type: 'function',
    inputs: [{ name: 'newRoyaltyRecipient', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'walletOfOwner',
    type: 'function',
    inputs: [{ name: '_owner', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256[]', internalType: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    name: 'withdrawRaised',
    type: 'function',
    inputs: [
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
];
