import type { GlobalThemeOverrides, MessageProviderProps } from 'naive-ui';
import { colors } from '~/tailwind.config';

type MessageThemeOverrides = NonNullable<MessageProviderProps['themeOverrides']>;
const messageOverrides: MessageThemeOverrides = {
  borderRadius: '8px',
  closeIconColor: colors.bg.DEFAULT,
  closeIconColorError: colors.bg.DEFAULT,
  closeIconColorHover: colors.bg.DEFAULT,
  closeIconColorHoverError: colors.bg.DEFAULT,
  closeIconColorHoverInfo: colors.bg.DEFAULT,
  closeIconColorHoverLoading: colors.bg.DEFAULT,
  closeIconColorHoverSuccess: colors.bg.DEFAULT,
  closeIconColorHoverWarning: colors.bg.DEFAULT,
  closeIconColorInfo: colors.bg.DEFAULT,
  closeIconColorLoading: colors.bg.DEFAULT,
  closeIconColorPressed: colors.bg.DEFAULT,
  closeIconColorPressedError: colors.bg.DEFAULT,
  closeIconColorPressedInfo: colors.bg.DEFAULT,
  closeIconColorPressedLoading: colors.bg.DEFAULT,
  closeIconColorPressedSuccess: colors.bg.DEFAULT,
  closeIconColorPressedWarning: colors.bg.DEFAULT,
  closeIconColorSuccess: colors.bg.DEFAULT,
  closeIconColorWarning: colors.bg.DEFAULT,
  color: colors.white.DEFAULT,
  colorError: colors.white.DEFAULT,
  colorInfo: colors.white.DEFAULT,
  colorLoading: colors.white.DEFAULT,
  colorSuccess: colors.white.DEFAULT,
  colorWarning: colors.white.DEFAULT,
  iconColor: colors.bg.DEFAULT,
  iconColorError: colors.bg.DEFAULT,
  iconColorInfo: colors.bg.DEFAULT,
  iconColorLoading: colors.bg.DEFAULT,
  iconColorSuccess: colors.bg.DEFAULT,
  iconColorWarning: colors.bg.DEFAULT,
  maxWidth: '380px',
  padding: '24px',
  textColor: colors.bg.DEFAULT,
  textColorError: colors.bg.DEFAULT,
  textColorInfo: colors.bg.DEFAULT,
  textColorLoading: colors.bg.DEFAULT,
  textColorSuccess: colors.bg.DEFAULT,
  textColorWarning: colors.bg.DEFAULT,
};

/**
 * Theme configs
 */
export const themeOverrides: GlobalThemeOverrides = {
  common: {
    baseColor: colors.bg.DEFAULT,
    bodyColor: colors.bg.light,
    errorColor: colors.pink,
    infoColor: colors.blue,
    primaryColor: colors.primary,
    primaryColorHover: colors.primary,
    primaryColorPressed: colors.primary,
    successColor: colors.green,
    warningColor: colors.yellow,
  },
  Alert: {},
  Button: {
    border: `1px solid ${colors.bg.lighter}`,
    borderDisabled: `1px solid ${colors.bg.lighter}`,
    borderError: `1px solid ${colors.bg.lighter}`,
    borderFocusError: `1px solid ${colors.bg.lighter}`,
    borderHoverError: `1px solid ${colors.bg.lighter}`,
    borderPressedError: `1px solid ${colors.bg.lighter}`,
    borderFocus: `1px solid ${colors.bg.lighter}`,
    borderHover: `1px solid ${colors.bg.lighter}`,
    borderPrimary: `1px solid ${colors.bg.lighter}`,
    borderFocusPrimary: `1px solid ${colors.bg.lighter}`,
    borderHoverPrimary: `1px solid ${colors.bg.lighter}`,
    borderPressedPrimary: `1px solid ${colors.bg.lighter}`,
    borderRadiusTiny: '0px',
    borderRadiusSmall: '8px',
    borderRadiusMedium: '8px',
    borderRadiusLarge: '8px',
    colorDisabledPrimary: colors.bg.lighter,
    colorInfo: colors.white.DEFAULT,
    colorHover: colors.bg.lighter,
    colorHoverError: colors.bg.lightTransparent,
    colorHoverInfo: colors.white.DEFAULT,
    colorFocusInfo: colors.white.DEFAULT,
    colorPressedInfo: colors.white.DEFAULT,
    colorDisabledInfo: colors.white.DEFAULT,
    colorQuaternary: 'transparent',
    colorQuaternaryHover: colors.primary,
    colorQuaternaryPressed: colors.primary,
    colorTertiaryHover: colors.bg.lighter,
    colorTertiaryPressed: colors.bg.lighter,
    fontSizeSmall: '14px',
    fontSizeMedium: '14px',
    fontSizeLarge: '14px',
    fontWeight: 'bold',
    heightTiny: '24px',
    heightSmall: '30px',
    heightMedium: '36px',
    heightLarge: '48px',
    paddingTiny: '1px',
    paddingSmall: '6px 12px',
    paddingMedium: '8px 16px',
    paddingLarge: '8px 24px',
    textColorGhostHover: 'inherit',
    textColorGhostHoverInfo: 'inherit',
    textColorGhostHoverSuccess: 'inherit',
    textColorGhostHoverPrimary: 'initial',
    textColorGhostHoverWarning: 'initial',
    textColorInfo: colors.bg.DEFAULT,
    textColorFocus: colors.white.DEFAULT,
    textColorError: colors.pink,
    textColorFocusError: colors.pink,
    textColorHoverError: colors.pink,
    textColorGhostHoverError: colors.pink,
    textColorTextHoverError: colors.pink,
    textColorPressedError: colors.pink,
    textColorTextError: colors.pink,
    textColorTertiary: colors.white.DEFAULT,
  },
  Card: {
    borderColor: colors.bg.lighter,
    borderRadius: '8px',
    color: colors.bg.DEFAULT,
    colorEmbedded: colors.bg.DEFAULT,
    colorEmbeddedModal: colors.bg.DEFAULT,
    colorEmbeddedPopover: colors.bg.DEFAULT,
    colorModal: colors.bg.DEFAULT,
    colorPopover: colors.bg.DEFAULT,
    colorTarget: colors.bg.DEFAULT,
    paddingSmall: '16px',
    paddingMedium: '32px',
    paddingLarge: '16px 56px 16px 56px',
    paddingHuge: '56px',
  },
  Checkbox: {
    border: `2px solid ${colors.hover}`,
    borderChecked: `2px solid ${colors.hover}`,
    borderFocus: `2px solid ${colors.hover}`,
    borderRadius: '4px',
    boxShadowFocus: 'none',
    colorChecked: colors.white.DEFAULT,
    fontSizeMedium: '14px',
    fontSizeLarge: '14px',
    labelPadding: '0 0 0 8px',
    sizeSmall: '16px',
    sizeMedium: '18px',
    sizeLarge: '24px',
    textColor: colors.white.DEFAULT,
  },
  Collapse: {
    dividerColor: `${colors.body}66`,
    titleFontWeight: 'bold',
  },
  DataTable: {
    borderColor: colors.bg.lighter,
    tdColor: colors.bg.DEFAULT,
    tdColorHover: colors.bg.dark,
    tdColorModal: colors.transparent,
    tdColorHoverModal: colors.bg.dark,
    tdTextColor: colors.white.DEFAULT,
    thColor: colors.bg.lightTransparent,
    thColorHover: colors.bg.lightTransparent,
    thColorHoverPopover: colors.bg.lightTransparent,
    thColorHoverModal: colors.bg.lightTransparent,
    thColorModal: colors.bg.lightTransparent,
    thColorPopover: colors.bg.lightTransparent,
    thColorSorting: colors.bg.lightTransparent,
    thColorSortingModal: colors.bg.lightTransparent,
    thColorSortingPopover: colors.bg.lightTransparent,
    thFontWeight: '600',
    thTextColor: colors.white.DEFAULT,
  },
  DatePicker: {
    panelBorderRadius: '0px',
  },
  Dialog: {
    border: `1px solid ${colors.bg.lighter}`,
    borderRadius: '0px',
    closeBorderRadius: '50%',
    closeColorHover: colors.white.DEFAULT,
    closeColorPressed: colors.white.DEFAULT,
    closeIconColor: colors.white.DEFAULT,
    closeIconColorPressed: colors.bg.DEFAULT,
    closeIconColorHover: colors.bg.DEFAULT,
    color: colors.bg.DEFAULT,
    contentMargin: '16px 0',
    titleFontSize: '20px',
  },
  Divider: {
    color: colors.white.DEFAULT,
  },
  Drawer: {
    color: colors.bg.DEFAULT,
    textColor: colors.white.DEFAULT,
    headerBorderBottom: `1px solid ${colors.bg.lighter}`,
    headerPadding: '40px 40px 20px',
    bodyPadding: '20px 40px',
    footerPadding: '20px 40px 40px',
  },
  Dropdown: {
    borderRadius: '8px',
    color: colors.bg.dark,
    fontSizeSmall: '12px',
    fontSizeMedium: '14px',
    fontSizeLarge: '16px',
    fontSizeHuge: '18px',
    optionColorActive: colors.bg.lighter,
    optionColorHover: colors.bg.lighter,
    optionTextColor: colors.white.DEFAULT,
    optionTextColorHover: colors.white.DEFAULT,
    optionTextColorActive: colors.white.DEFAULT,
    optionTextColorChildActive: colors.white.DEFAULT,
    padding: '16px 12px',
  },
  Form: {
    feedbackFontSizeSmall: '10px',
    feedbackFontSizeMedium: '10px',
    feedbackFontSizeLarge: '10px',
    feedbackHeightSmall: '20px',
    feedbackHeightMedium: '20px',
    feedbackHeightLarge: '20px',
    labelFontSizeTopSmall: '10px',
    labelFontSizeLeftSmall: '10px',
    labelFontSizeLeftMedium: '12px',
    labelFontSizeTopMedium: '12px',
    labelFontSizeLeftLarge: '14px',
    labelFontSizeTopLarge: '14px',
    feedbackPadding: '2px 0 0 2px',
    labelPaddingVertical: '0 0 8px',
    labelTextColor: colors.white.DEFAULT,
  },
  Input: {
    border: `1px solid ${colors.bg.lighter}`,
    borderFocus: `1px solid ${colors.white}`,
    borderHover: `1px solid ${colors.hover}`,
    borderError: `1px solid ${colors.pink}`,
    borderFocusError: `1px solid ${colors.pink}`,
    borderHoverError: `1px solid ${colors.pink}`,
    borderDisabled: `1px solid ${colors.bg.lighter}`,
    borderRadius: '8px',
    boxShadowFocus: 'none',
    boxShadowFocusError: 'none',
    boxShadowFocusWarning: 'none',
    caretColor: colors.white.DEFAULT,
    clearSize: '24px',
    clearColorHover: colors.white.primary,
    color: colors.bg.light,
    colorDisabled: colors.bg.light,
    colorFocus: colors.bg.light,
    colorFocusError: colors.bg.light,
    colorFocusWarning: colors.bg.light,
    fontSizeTiny: '12px',
    fontSizeSmall: '14px',
    fontSizeMedium: '14px',
    fontSizeLarge: '16px',
    groupLabelTextColor: colors.white.DEFAULT,
    heightTiny: '24px',
    heightSmall: '30px',
    heightMedium: '36px',
    heightLarge: '48px',
    iconSize: '24px',
    iconColorHover: colors.white.primary,
    paddingTiny: '10px',
    paddingSmall: '12px',
    paddingMedium: '20px',
    paddingLarge: '20px',
    placeholderColor: colors.placeholder,
    suffixTextColor: colors.white.primary,
    textColor: colors.white.DEFAULT,
    textColorDisabled: 'rgba(153, 153, 153, 0.64)',
  },
  InputNumber: {
    peers: {
      Button: {
        color: colors.bg.light,
        textColor: colors.bg.light,
        textColorTextHover: colors.white.DEFAULT,
      },
    },
  },
  Layout: {
    textColor: colors.white.DEFAULT,
    siderBorderColor: colors.bg.lighter,
  },
  Menu: {
    borderColorHorizontal: colors.yellow,
    borderRadius: '0px',
    groupTextColorInverted: colors.violet,
    itemColorHoverInverted: colors.bg.lighter,
    itemColorActiveInverted: colors.bg.lighter,
    itemColorActiveHoverInverted: colors.bg.lighter,
    itemColorActiveCollapsedInverted: colors.bg.lighter,
    itemHeight: '40px',
    itemIconColorInverted: colors.white.DEFAULT,
    itemIconColorActiveInverted: colors.white.DEFAULT,
    itemIconColorHoverInverted: colors.white.DEFAULT,
    itemIconColorActiveHoverInverted: colors.white.DEFAULT,
    itemIconColorChildActiveInverted: colors.white.DEFAULT,
    itemIconColorChildActiveHoverInverted: colors.white.DEFAULT,
    itemTextColorInverted: colors.white.DEFAULT,
    itemTextColorActiveInverted: colors.white.DEFAULT,
    itemTextColorHoverInverted: colors.white.DEFAULT,
    itemTextColorChildActiveHoverInverted: colors.white.DEFAULT,
    itemTextColorHorizontal: colors.white.terciary,
    itemTextColorActiveHorizontal: colors.white.DEFAULT,
    itemTextColorActiveHoverHorizontal: colors.white.DEFAULT,
    itemTextColorHoverHorizontal: colors.body,
    itemTextColor: colors.white.DEFAULT,
  },
  Message: messageOverrides,
  Modal: {
    color: colors.bg.DEFAULT,
    peers: {
      Card: {
        borderColor: colors.bg.lighter,
        borderRadius: '8px',
        paddingSmall: '28px 40px',
        paddingMedium: '32px 56px',
        paddingLarge: '32px 56px',
        paddingHuge: '32px 56px',
      },
      Dialog: {
        border: `1px solid ${colors.bg.lighter}`,
        borderRadius: '8px',
        closeColorHover: 'inherit',
        closeMargin: '-24px -24px 0 0',
        contentMargin: '16px 0',
        padding: '56px 56px 32px',
      },
    },
  },
  Pagination: {
    peers: {
      Select: {
        peers: {
          InternalSelectMenu: {
            paddingSmall: '4px 8px',
            paddingMedium: '4px 10px',
            paddingLarge: '4px 20px',
          },
        },
      },
    },
  },
  Popconfirm: {},
  Popover: {
    arrowHeight: '16px',
    border: `1px solid ${colors.bg.lighter}`,
    borderHover: `2px solid ${colors.bodyDark}`,
    borderRadius: '8px',
    color: colors.bg.dark,
    spaceArrow: '16px',
  },
  Progress: {
    fillColor: colors.green,
    fillColorInfo: colors.green,
    fillColorError: colors.pink,
    fillColorSuccess: colors.green,
    railColor: colors.bg.lighter,
    railHeight: '4px',
  },
  Radio: {
    boxShadow: `inset 0 0 0 1px ${colors.body}`,
    fontSizeSmall: '12px',
    fontSizeMedium: '14px',
    fontSizeLarge: '16px',

    radioSizeSmall: '16px',
    radioSizeMedium: '20px',
    radioSizeLarge: '24px',

    textColor: colors.white.DEFAULT,

    buttonBorderColor: colors.bg.lighter,
    buttonBorderColorActive: colors.body,
    buttonBorderColorHover: colors.body,

    buttonBorderRadius: '0px',
    buttonColor: colors.bg.light,
    buttonColorActive: colors.bg.lighter,
    colorDisabled: colors.bg.DEFAULT,

    buttonTextColor: colors.white.DEFAULT,
    buttonTextColorActive: colors.white.DEFAULT,
    buttonTextColorHover: colors.white.DEFAULT,
    textColorDisabled: colors.white.DEFAULT,

    buttonBoxShadow: 'none',
    buttonBoxShadowFocus: 'none',
    buttonBoxShadowHover: 'none',
  },
  Select: {
    peers: {
      InternalSelection: {
        arrowColor: colors.white.DEFAULT,
        arrowSize: '24px',
        border: `1px solid ${colors.bg.lighter}`,
        borderActive: `1px solid ${colors.white}`,
        borderFocus: `1px solid ${colors.white}`,
        borderHover: `1px solid ${colors.body}`,
        borderRadius: '8px',
        boxShadowActive: 'none',
        boxShadowFocus: 'none',
        boxShadowHover: 'none',
        color: colors.bg.light,
        colorActive: colors.bg.light,
        colorDisabled: colors.bg.DEFAULT,
        heightLarge: '48px',
        heightMedium: '36px',
        heightSmall: '30px',
        heightTiny: '32px',
      },
      InternalSelectMenu: {
        borderRadius: '8px',
        color: colors.bg.dark,
        optionCheckColor: colors.bg.lighter,
        optionColorActive: colors.bg.lighter,
        optionColorActivePending: colors.bg.lighter,
        optionColorPending: colors.bg.lighter,
        optionHeightLarge: '48px',
        optionHeightMedium: '36px',
        optionHeightSmall: '30px',
        optionHeightTiny: '26px',
        paddingSmall: '0px 4px',
        paddingMedium: '0px 8px',
        paddingLarge: '0px 20px',
        actionTextColor: colors.white.DEFAULT,
        optionTextColor: colors.white.DEFAULT,
        optionTextColorActive: colors.white.DEFAULT,
        optionTextColorPressed: colors.white.DEFAULT,
      },
    },
  },
  Skeleton: {
    color: colors.bg.light,
    colorEnd: colors.bg.lighter,
  },
  Switch: {
    boxShadowFocus: 'none',
    buttonBoxShadow: 'none',
    buttonColor: colors.white.primary,
    buttonHeightMedium: '19px',
    buttonWidthMedium: '19px',
    railColor: colors.bg.lightTransparent,
    railColorActive: colors.bg.lightTransparent,
    railWidthMedium: '56px',
    railHeightMedium: '33px',
  },
  Table: {
    borderColor: colors.bg.lighter,
    borderRadius: '0px',
    tdColor: colors.transparent,
    tdColorHover: colors.bg.lightTransparent,
    tdColorModal: colors.bg.DEFAULT,
    tdTextColor: colors.white.DEFAULT,
    thColor: colors.transparent,
    thColorModal: colors.bg.light,
    thFontWeight: '700',
    thTextColor: colors.white.DEFAULT,
  },
  Tabs: {
    colorSegment: colors.bg.DEFAULT,
    panePaddingMedium: '32px 0 0',
    paneTextColor: colors.white.DEFAULT,
    tabBorderColor: colors.bg.lighter,
    tabBorderRadius: '0',
    tabColor: colors.green,
    tabColorSegment: colors.bg.light,
    tabGapLargeBar: '4vw',
    tabPaddingMediumSegment: '16px 0',
    tabTextColorLine: colors.bodyDark,
    tabTextColorActiveLine: colors.white.DEFAULT,
    tabTextColorHoverLine: colors.white.DEFAULT,
    tabTextColorSegment: colors.bodyDark,
    tabTextColorActiveSegment: colors.white.DEFAULT,
  },
  Tag: {
    border: `1px solid ${colors.body}`,
    borderError: `1px solid ${colors.pink}`,
    borderInfo: `1px solid ${colors.blue}`,
    borderPrimary: `1px solid ${colors.primary}`,
    borderSuccess: `1px solid ${colors.green}`,
    borderWarning: `1px solid ${colors.orange}`,
    colorError: colors.pink,
    colorInfo: colors.blue,
    colorSuccess: colors.green,
    colorWarning: colors.orange,
    fontSizeTiny: '10px',
    fontSizeSmall: '12px',
    fontSizeMedium: '14px',
    fontSizeLarge: '18px',
    fontWeightStrong: '700',
    heightTiny: '24px',
    heightSmall: '28px',
    heightMedium: '32px',
    heightLarge: '36px',
    padding: '4px 10px',
    paddingTiny: '4px 10px',
    paddingSmall: '4px 12px',
    paddingMedium: '4px 14px',
    paddingLarge: '4px 16px',
    paddingHuge: '4px 18px',
    textColor: colors.body,
    textColorInfo: colors.blue,
    textColorError: colors.bg.dark,
    textColorSuccess: colors.bg.dark,
    textColorWarning: colors.bg.dark,
  },
  Tooltip: {
    borderRadius: '6px',
    boxShadow: 'none',
    color: colors.bg.lighter,
    padding: '8px 12px',
    textColor: colors.white.DEFAULT,
  },
  Typography: {
    headerMargin5: '32px 0 16px 0',
  },
  Upload: {
    draggerBorder: `none`,
    draggerBorderHover: `none`,
    draggerColor: colors.bg.light,
  },
};
