import packageConfig from '../../package.json';

const config: ConfigInterface = {
  VERSION: packageConfig.version || '1.0.0',
  url: 'https://app.apillon.io',
  apiUrl: 'https://console-api.apillon.io',
  oauthUrl: 'https://oauth.apillon.io',
  adminUrl: 'https://admin.apillon.io',
  mailerLiteSubscribeUrl: 'https://landing.mailerlite.com/webforms/landing/i9f9l9',
  captchaKey: 'f5f700a0-51b2-49f3-9ba5-46c7fe146af0',
  githubId: '70d0aa8922fe05268341',
  gtmId: 'GTM-P7V3D3P6',
  nctrContract: '0xc27e62A737C7474AD9EEF6C493Ed68c71dB80A65',
  publishedFeatures: [
    'ACCESS',
    'API_KEYS',
    'AUTHENTICATION',
    'BILLING',
    'CAPTCHA_LOGIN',
    'COMPUTING',
    'DISCORD',
    'EMBEDDED_WALLET',
    'HOSTING',
    'KILT_LOGIN',
    'MARKETING',
    'NFT',
    'NFT_NESTABLE',
    'PREBUILD_SOLUTIONS',
    'PROJECT',
    'PROJECT_ON_STARTUP',
    'PROJECT_SETTINGS',
    'REFERRAL',
    'SERVICES',
    'SOCIAL',
    'STORAGE',
    'WALLET_LOGIN',
  ],
  betaFeatures: ['ASSET_HUB', 'EMBEDDED_WALLET', 'SMART_CONTRACTS'],
};

export default config;
