export enum SolutionKey {
  ENCRYPTION = 'encryption',
  FILE_SHARING = 'fileSharing',
  NFT_AIRDROP = 'nftAirdrop',
  NFT_COLLECTION = 'nftCollection',
  NFT_CONTENT_DELIVERY = 'nftContentDelivery',
  NFT_DROP = 'nftDrop',
  NFT_EMAIL_SIGNUP_AIRDROP = 'nftEmailSignupAirdrop',
  NFT_LOYALTY = 'nftLoyalty',
  NFT_MEMBERSHIP = 'nftMembership',
  NFT_POAP = 'nftPoap',
  NFT_WHITELIST_CLAIM = 'nftWhitelistClaim',
  OPEN_GOV = 'openGov',
  TOKEN_GATING = 'tokenGating',
  WALLET = 'wallet',
  EMBEDDED_WALLET = 'embeddedWallet',
}
